[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#6366f1"
backgroundColor = "#0f0f23"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
